In [1]:
import pandas as pd

In [2]:
deployments = pd.read_csv("../data/raw/deployments.csv")

In [3]:
deployments.head()

,deployment_id,platform,name,proposals_count,unique_voters,votes_count,estimated_vp,website,additional
0,0x0017a25385931ee690dc09df6cca919d1cd007b2,aragon,NaN,2,2.0,2,1.000000e+37,https://etherscan.io/address/0x0017a25385931ee...,NaN
1,0x001cd74c9a99b6c68e93fe69595124407b37aa8e,aragon,shilldao,17,216.0,216,0.000000e+00,https://etherscan.io/address/0x001cd74c9a99b6c...,NaN
2,0x0068990f8910e502dd41eb71fbc506936ca100af,aragon,NaN,0,0.0,0,0.000000e+00,https://etherscan.io/address/0x0068990f8910e50...,NaN
3,0x00b424842685f69912cfd93af7293602c973bf56,aragon,NaN,0,0.0,0,0.000000e+00,https://etherscan.io/address/0x00b424842685f69...,NaN
4,0x00ccb72bd1f72882d89774d9acccce616ed9227d,aragon,NaN,25,16.0,16,0.000000e+00,https://etherscan.io/address/0x00ccb72bd1f7288...,NaN

In [4]:
deployments.shape

(86489, 9)

In [5]:
deployments.columns

Index(['deployment_id', 'platform', 'name', 'proposals_count', 'unique_voters',
       'votes_count', 'estimated_vp', 'website', 'additional'],
      dtype='str')

In [6]:
deployments.dtypes

deployment_id          str
platform               str
name                   str
proposals_count      int64
unique_voters      float64
votes_count          int64
estimated_vp       float64
website                str
additional             str
dtype: object

In [7]:
deployments.isna().sum()

deployment_id          0
platform               0
name                3138
proposals_count        0
unique_voters          0
votes_count            0
estimated_vp       71952
website            12135
additional         69797
dtype: int64

In [8]:
deployments.info()

<class 'pandas.DataFrame'>
RangeIndex: 86489 entries, 0 to 86488
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   deployment_id    86489 non-null  str
 1   platform         86489 non-null  str
 2   name             83351 non-null  str
 3   proposals_count  86489 non-null  int64
 4   unique_voters    86489 non-null  float64
 5   votes_count      86489 non-null  int64
 6   estimated_vp     14537 non-null  float64
 7   website          74354 non-null  str
 8   additional       16692 non-null  str
dtypes: float64(2), int64(2), str(5)
memory usage: 5.9 MB

In [9]:
proposals = pd.read_csv("../data/raw/proposals.csv")

C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\155405936.py:1: DtypeWarning: Columns (7: platform_deployment_id) have mixed types. Specify dtype option on import or set low_memory=False.
  proposals = pd.read_csv("../data/raw/proposals.csv")

In [10]:
proposals.head()

,proposal_id,deployment_id,platform,date,votes_count,total_vp,author,platform_deployment_id
0,appaddress:0x00299ee9faf692b8e48b0cc7a9c1805dd...,0xc31691d35e890d70d2357f010406a28ae0fce74e,aragon,2019-05-23 09:16:33,0.0,1.000000e+18,0xb2a5c803247e275a2b9a4bd0d2f28e8183c607dd,NaN
1,appaddress:0x00299ee9faf692b8e48b0cc7a9c1805dd...,0xc31691d35e890d70d2357f010406a28ae0fce74e,aragon,2019-05-23 09:16:58,1.0,1.000000e+18,0xb2a5c803247e275a2b9a4bd0d2f28e8183c607dd,NaN
2,appaddress:0x00299ee9faf692b8e48b0cc7a9c1805dd...,0xc31691d35e890d70d2357f010406a28ae0fce74e,aragon,2019-05-23 09:30:04,2.0,1.000000e+18,0xb2a5c803247e275a2b9a4bd0d2f28e8183c607dd,NaN
3,appaddress:0x005aa691246cbaae1ace1f620f1e9b9bd...,0x8fa64f19ab40ef70de272d132704b1551e6075fa,aragon,2020-04-12 15:11:56,0.0,1.000000e+18,0x9cf0029dd2acf7415d460d93b93ffc5daeb187ae,NaN
4,appaddress:0x005aa691246cbaae1ace1f620f1e9b9bd...,0x8fa64f19ab40ef70de272d132704b1551e6075fa,aragon,2020-04-12 15:27:27,1.0,1.000000e+18,0x9cf0029dd2acf7415d460d93b93ffc5daeb187ae,NaN

In [11]:
proposals.shape

(370133, 8)

In [12]:
proposals.columns

Index(['proposal_id', 'deployment_id', 'platform', 'date', 'votes_count',
       'total_vp', 'author', 'platform_deployment_id'],
      dtype='str')

In [13]:
proposals.dtypes

proposal_id                   str
deployment_id                 str
platform                      str
date                          str
votes_count               float64
total_vp                  float64
author                        str
platform_deployment_id        str
dtype: object

In [14]:
proposals.isna().sum()

proposal_id                    0
deployment_id              20112
platform                       0
date                          79
votes_count                    0
total_vp                   20112
author                     58992
platform_deployment_id    350021
dtype: int64

In [15]:
proposals.info()

<class 'pandas.DataFrame'>
RangeIndex: 370133 entries, 0 to 370132
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   proposal_id             370133 non-null  str
 1   deployment_id           350021 non-null  str
 2   platform                370133 non-null  str
 3   date                    370054 non-null  str
 4   votes_count             370133 non-null  float64
 5   total_vp                350021 non-null  float64
 6   author                  311141 non-null  str
 7   platform_deployment_id  20112 non-null   str
dtypes: float64(2), str(6)
memory usage: 22.6 MB

In [16]:
votes_sample = pd.read_csv(
    "../data/raw/votes.csv",
    nrows=5
)

In [17]:
votes_sample.head()

,vote_id,proposal_id,deployment_id,platform,date,voter,choice,weight
0,0x0-voter:0x0000008cc20c51c19b3557bf95481b6073...,appAddress:0x1115c9b3168563354137cdc60efb66552...,0x79cf3e23eded0fc20992b79acb3b3ffb7c6799b4,aragon,2020-09-29 01:11:17,0x1115c9b3168563354137cdc60efb66552dd50678-vot...,True,1
1,0x0-voter:0x000000de5f9e90ce604da5fd78acd6fae7...,appAddress:0x9b8e397c483449623525efda8f80d9b52...,0xf4dacf2edb6e2bd88eb90c3aef1e510153d38579,aragon,2020-01-24 09:38:06,0x9b8e397c483449623525efda8f80d9b52481a3a1-vot...,False,1
2,0x0-voter:0x00000b43329dc00f7eb64b8f9ce210a4b8...,appAddress:0xc50f36e3db27d3f4e303384ca85503baa...,0xc1a90f60e32321c3c12c6996d57608cfa439641e,aragon,2022-04-13 22:30:44,0xc50f36e3db27d3f4e303384ca85503baa9b02510-vot...,True,250000000000000000000000
3,0x0-voter:0x002b3d4527a5d7799cc8714733278b675e...,appAddress:0xa1316e773519bdc6f135509962b51f318...,0xf95aeaadc21d0a0ad51f29a01ecb226453210cd0,aragon,2019-11-27 16:15:11,0xa1316e773519bdc6f135509962b51f318869cc25-vot...,True,100000000000000000000
4,0x0-voter:0x0030026755d09ee4b809b7e968dfe1b004...,appAddress:0x7bc51cfcc7a538a6cce75d42285502937...,0x5ad614d836912ee578636d18edb01f2af2c74846,aragon,2019-04-18 01:03:15,0x7bc51cfcc7a538a6cce75d42285502937b5f3c2d-vot...,True,1000000000000000000

In [18]:
votes_chunks = pd.read_csv(
    "../data/raw/votes.csv",
    chunksize=100_000
)

In [19]:
first_chunk = next(votes_chunks)

C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\2322993396.py:1: DtypeWarning: Columns (7: weight) have mixed types. Specify dtype option on import or set low_memory=False.
  first_chunk = next(votes_chunks)

In [20]:
first_chunk.shape

(100000, 8)

In [21]:
first_chunk.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   vote_id        100000 non-null  str
 1   proposal_id    100000 non-null  str
 2   deployment_id  100000 non-null  str
 3   platform       100000 non-null  str
 4   date           90293 non-null   str
 5   voter          100000 non-null  str
 6   choice         99396 non-null   str
 7   weight         100000 non-null  object
dtypes: object(1), str(7)
memory usage: 6.1+ MB

In [22]:
first_chunk.isna().sum()

vote_id             0
proposal_id         0
deployment_id       0
platform            0
date             9707
voter               0
choice            604
weight              0
dtype: int64

In [23]:
first_chunk["platform"].value_counts()

platform
daohaus     51129
aragon      26833
daostack    12331
realms       9707
Name: count, dtype: int64

In [24]:
first_chunk[first_chunk["date"].isna()]["platform"].value_counts()

platform
realms    9707
Name: count, dtype: int64

In [25]:
first_chunk[first_chunk["choice"].isna()]["platform"].value_counts()

platform
realms    604
Name: count, dtype: int64

In [26]:
votes_chunks = pd.read_csv(
    "../data/raw/votes.csv",
    chunksize=1_000_000
)

In [27]:
total_votes = 0

for chunk in votes_chunks:
    total_votes += len(chunk)

total_votes

C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\3964973578.py:3: DtypeWarning: Columns (4: date, 7: weight) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in votes_chunks:
C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\3964973578.py:3: DtypeWarning: Columns (4: date, 6: choice) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in votes_chunks:
C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\3964973578.py:3: DtypeWarning: Columns (7: weight) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in votes_chunks:
C:\Users\alexs\AppData\Local\Temp\ipykernel_22168\3964973578.py:3: DtypeWarning: Columns (0: vote_id, 1: proposal_id) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in votes_chunks:

11638348